In [1]:
# creating numpy / n-d arrays
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5])         #print array
arr1 

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)                        #type of array

numpy.ndarray

In [7]:
arr2=np.array([[1,2,3],[4,5,6,],[7,8,9]])          #2d array
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr3=np.zeros([2,3])                  #contiain 0 in given row and column 
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
arr4=np.ones([3,4])                # contain 1 in given row and column
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
arr5=np.identity(3)               #identity matrix of given order
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
arr6=np.arange(10)               # give range of number in  array start from 0 and not include the given number

In [13]:
arr6


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr7=np.arange(5,14)            #give range of number in array start from given no. to not included that number 
arr7

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13])

In [15]:
arr8=np.arange(5,14,3)          # given range of number with jump 
arr8

array([ 5,  8, 11])

In [18]:
arr9=np.linspace(10,20,10)      # linear space ( the diff between two point is same )
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [17]:
arr10=arr9.copy()               #copy the array
arr10

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])