In [2]:
import numpy as np                 #property and attributes

In [5]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [6]:
arr1.shape               #give number of row and column

(5,)

In [9]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr2.shape               #give number of row and column

(3, 3)

In [11]:
arr2.ndim              #give dimensions of array

2

In [12]:
arr1.ndim

1

In [13]:
arr1.size              #size of array (number of elements)

5

In [14]:
arr2.size

9

In [15]:
arr2.itemsize              #size of 1 element (8byte)

8

In [16]:
arr1.dtype               #data type

dtype('int64')

In [17]:
arr2.dtype

dtype('int64')

In [21]:
arr1.astype("float")         #conversion of datatype
                            #it doesn't modify the exisiting array but it make the new array 


array([1., 2., 3., 4., 5.])

In [20]:
arr1.dtype

dtype('int64')