In [1]:
import numpy as np   #indexing,slicing and iteration 

In [2]:
arr1=np.arange(50)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [4]:
arr1=np.arange(50).reshape(5,10)          #for reshaping
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [5]:
arr1[2]                                  # for 3rd row

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [6]:
arr1[:,2]                               # for 3rd column

array([ 2, 12, 22, 32, 42])

In [8]:
arr1[:,3:6]                            # for 4th to 6th column

array([[ 3,  4,  5],
       [13, 14, 15],
       [23, 24, 25],
       [33, 34, 35],
       [43, 44, 45]])

In [9]:
arr1[2:4,4:6]                        # for 24,25,34,35 

array([[24, 25],
       [34, 35]])

In [11]:
for i in arr1:                     # iterate over row
    print(i)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24 25 26 27 28 29]
[30 31 32 33 34 35 36 37 38 39]
[40 41 42 43 44 45 46 47 48 49]


In [12]:
for i in np.nditer(arr1):       # iterate every elements 
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
