In [1]:
import numpy as np                     #operations

In [2]:
arr1=np.array([1,2,3,4,5,6])

In [3]:
arr2=np.array([4,5,6,7,8,9])

In [4]:
arr1-arr2                         # element  wise subtraction

array([-3, -3, -3, -3, -3, -3])

In [5]:
arr1*arr2                        # element wise multiplication

array([ 4, 10, 18, 28, 40, 54])

In [6]:
arr1*3                          # every element will multiply with 3

array([ 3,  6,  9, 12, 15, 18])

In [7]:
arr2>5                   # compare every element

array([False, False,  True,  True,  True,  True])

In [8]:
arr3=np.arange(6).reshape(2,3)

In [9]:
arr4=np.arange(6,12).reshape(3,2)

In [10]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [12]:
arr3.dot(arr4)             #dot product 

array([[ 28,  31],
       [100, 112]])

In [18]:
arr4.max()               #maximum 

np.int64(11)

In [19]:
arr4.min()               # minimum

np.int64(6)

In [20]:
arr4.max(axis=0)          #every column maximum elemenet

array([10, 11])

In [21]:
arr4.min(axis=1)            # every row minimum element

array([ 6,  8, 10])

In [22]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [23]:
arr4.sum()           # sum of all elements

np.int64(51)

In [24]:
arr4.sum(axis=0)     # every column sum

array([24, 27])

In [25]:
arr4.mean()         # mean of all elements   also applicable for rows and column by using axis

np.float64(8.5)

In [26]:
arr4.std()          # standard deviation     also applicable for rows and column by using axis

np.float64(1.707825127659933)

In [27]:
np.sin(arr4)             #sin

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [28]:
np.median(arr4)           # median

np.float64(8.5)

In [29]:
np.exp(arr4)               # exponent  

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])