In [1]:
import numpy as np         # reshaping numpy arrays

In [2]:
arr=np.arange(6,12).reshape(3,2)

In [3]:
arr

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [6]:
arr.ndim              # dimension of array

2

In [7]:
arr.ravel()           # higher dimension to 1 dimension

array([ 6,  7,  8,  9, 10, 11])

In [8]:
arr.transpose()      #transpose

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [9]:
arr1=np.arange(6).reshape(2,3)

In [10]:
arr2=np.arange(12,18).reshape(2,3)

In [11]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
arr2

array([[12, 13, 14],
       [15, 16, 17]])

In [13]:
np.hstack((arr1,arr2))              # horizontal stack

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [16]:
 np.vstack((arr1,arr2))             # vertical stack

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [18]:
np.hsplit(arr1,3)                 # horizontal split

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [19]:
np.vsplit(arr1,2)                # vertical split

[array([[0, 1, 2]]), array([[3, 4, 5]])]