In [2]:
import numpy as np    # fancy indexing & indexing with boolean arrays 

In [3]:
arr=np.arange(24).reshape(6,4)

In [4]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [6]:
arr[[0,2,4]]           # 1,3 and 5 row

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [7]:
arr1=np.random.randint(low=1,high=100,size=20).reshape(4,5)           # random array
arr1   

array([[47, 13,  2, 16, 78],
       [80, 56, 76, 84, 15],
       [ 9, 14, 86, 11, 68],
       [21, 97, 68, 60, 99]], dtype=int32)

In [10]:
arr1[0]                             # first row

array([47, 13,  2, 16, 78], dtype=int32)

In [11]:
arr1[0][2]                      # first row third element

np.int32(2)

In [12]:
 arr1[arr1>50]                        # element greater than 50   & indxeing using boolean arrays

array([78, 80, 56, 76, 84, 86, 68, 97, 68, 60, 99], dtype=int32)

In [13]:
arr1[(arr1>50) & (arr1%2!=0)]

array([97, 99], dtype=int32)